Features/lesson2
hahocok/java-lessons pull request #7
Opened 2020-10-21 08:52 UTC by hahocok

2020-10-22 06:47 UTC, DeltAagent00 requested changes

2020-10-22 06:47 UTC, DeltAagent00 commented on lesson2/Main.java
> +        if (arrs.length > 4 || arrs[0].length > 4) {
а если массив будет меньше чем 4*4?

2020-10-22 06:47 UTC, DeltAagent00 commented on lesson2/Main.java
> +        if (arrs.length > 4 || arrs[0].length > 4) {
что за магические числа? все константы нужно описывать что это такое и не гадать потом почему такое значение, и если это число потом измениться, чтобы не искать по всему коду к чему оно относится, а поменять в одном месте

2020-10-26 07:28 UTC, DeltAagent00 commented on lesson2/Main.java
>              throw new MySizeArrayException(4);
А если у тебя изменится MAX_ARR_SIZE, число 4 что будет обозначать?

2020-10-28 07:18 UTC, DeltAagent00 requested changes

2020-10-28 07:18 UTC, DeltAagent00 commented on lesson2/Main.java
>              throw new MySizeArrayException(4);
зачем передавать число 4 в эксепшен?

2020-10-29 07:26 UTC, hahocok commented on lesson2/Main.java
>              throw new MySizeArrayException(4);
для обработки ошибки и вывода лога

2020-10-29 07:37 UTC, DeltAagent00 approved these changes

2020-10-29 07:37 UTC, closed without merging